# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/home/simon/IdeaProjects/XeneonEdge_Linux;/home/simon/IdeaProjects/XeneonEdge_Linux/build-release")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libqt6svg6, qt6-wayland, qml6-module-qtcore, qml6-module-qtquick, qml6-module-qtquick-controls, qml6-module-qtquick-dialogs, qml6-module-qtquick-effects, qml6-module-qtquick-layouts, qml6-module-qtquick-shapes, qml6-module-qtquick-window, qml6-module-qtqml-workerscript")
set(CPACK_DEBIAN_PACKAGE_SECTION "utils")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS "ON")
set(CPACK_DEBIAN_PACKAGE_VERSION "1.0.0+19.g5b8c8c2")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/home/simon/.local/cmake-4.2.0-linux-x86_64/share/cmake-4.2/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "XeneonEdgeLinuxHub built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "/home/simon/IdeaProjects/XeneonEdge_Linux;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/usr/lib/cmake/Qt6;/usr/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/usr/lib/cmake/Qt6/3rdparty/kwin")
set(CPACK_NSIS_DISPLAY_NAME "xeneon-edge-hub 1.0.0-19-g5b8c8c2")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "xeneon-edge-hub 1.0.0-19-g5b8c8c2")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/simon/IdeaProjects/XeneonEdge_Linux/build-release/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "Simon Kreitmayer <simon.kreitmayer@skyphoenix-it.com>")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/simon/.local/cmake-4.2.0-linux-x86_64/share/cmake-4.2/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Native Linux widget dashboard for the Corsair Xeneon Edge and other secondary touchscreens")
set(CPACK_PACKAGE_FILE_NAME "xeneon-edge-hub-1.0.0-19-g5b8c8c2-Source")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/skyphoenix-it/skyphoenix-edgehub-linux")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "xeneon-edge-hub 1.0.0-19-g5b8c8c2")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "xeneon-edge-hub 1.0.0-19-g5b8c8c2")
set(CPACK_PACKAGE_NAME "xeneon-edge-hub")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "SKYPhoenix IT")
set(CPACK_PACKAGE_VERSION "1.0.0-19-g5b8c8c2")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PACKAGING_INSTALL_PREFIX "/usr")
set(CPACK_PROJECT_CONFIG_FILE "/home/simon/IdeaProjects/XeneonEdge_Linux/build-release/xeneon-cpack-generator-preflight.cmake")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/simon/IdeaProjects/XeneonEdge_Linux/LICENSE")
set(CPACK_RESOURCE_FILE_README "/home/simon/.local/cmake-4.2.0-linux-x86_64/share/cmake-4.2/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/home/simon/.local/cmake-4.2.0-linux-x86_64/share/cmake-4.2/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_FILE_NAME "RPM-DEFAULT")
set(CPACK_RPM_PACKAGE_GROUP "Applications/System")
set(CPACK_RPM_PACKAGE_LICENSE "(MIT OR Apache-2.0) AND MIT AND OFL-1.1 AND BSD-3-Clause AND MPL-2.0 AND Unicode-3.0")
set(CPACK_RPM_PACKAGE_REQUIRES "qt6-qtbase >= 6.9, qt6-qtdeclarative, qt6-qtsvg, qt6-qtwayland")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_RPM_PACKAGE_VERSION "1.0.0+19.g5b8c8c2")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/simon/IdeaProjects/XeneonEdge_Linux;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/simon/IdeaProjects/XeneonEdge_Linux/build-release/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "xeneon-edge-hub-1.0.0-19-g5b8c8c2-Source")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")
set(CPACK_XENEON_NATIVE_PACKAGE_VERSION "1.0.0+19.g5b8c8c2")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/simon/IdeaProjects/XeneonEdge_Linux/build-release/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
