#!/usr/bin/env bash
# OpenCode shim. Headless: `opencode run --format json`, session resume via
# --session <id>. Local LLMs come from the repo's opencode.json provider block
# (@ai-sdk/openai-compatible; Ollama/LM Studio/llama.cpp/any OpenAI-compatible URL) —
# pass the model as provider/model in AF_MODEL. Docs (accessed 2026-07-18):
# opencode.ai/docs/cli.
#
# Permission model (review finding CXR-003/KF-H14): supervised runs NEVER use --auto.
# Instead they select a generated agent profile whose permission map contains only
# explicit allow/deny decisions (no interactive asks to auto-approve) and denies
# external-directory access:
#   workspace-write -> --agent af-supervised-writer
#   read-only       -> --agent af-supervised-readonly
# Both profiles are generated by render.py into .opencode/agents/.
source "$(dirname "$0")/provider-common.sh"
af_guard_real_run

case "${AF_COMMAND_MODE:-workspace-write}" in
  workspace-write) AF_AGENT="af-supervised-writer" ;;
  read-only)       AF_AGENT="af-supervised-readonly" ;;
  *)
    echo "provider-opencode.sh: unsupported AF_COMMAND_MODE '${AF_COMMAND_MODE:-}'" \
         "(supported: workspace-write, read-only)" >&2
    exit 2 ;;
esac

cd "$AF_WORKDIR"
ARGS=(run --format json --model "$AF_MODEL" --agent "$AF_AGENT")
[[ -n "${AF_SESSION_REF:-}" ]] && ARGS+=(--session "$AF_SESSION_REF")

RAW_FILE="$(af_mktemp_raw)"
trap 'rm -f "$RAW_FILE"' EXIT
set +e
# </dev/null: the prompt travels as an argv value; stdin is unused and must be
# explicitly closed — an inherited interactive stdin would let the CLI block forever
# waiting for EOF (root cause of the shim-test hangs; see final report).
af_with_timeout opencode "${ARGS[@]}" "$(cat "$AF_PROMPT_FILE")" </dev/null >"$RAW_FILE" 2>>"${AF_LOG_FILE:-/dev/null}"
RC=$?
set -e

python3 - "$RC" "$RAW_FILE" "${AF_SESSION_REF:-}" <<'PY'
import json, sys
rc = int(sys.argv[1]); ref = sys.argv[3] or None
text = []; kind = "completed"
with open(sys.argv[2], encoding="utf-8", errors="replace") as f:
    raw = f.read()
for line in raw.splitlines():
    line = line.strip()
    if not line:
        continue
    try:
        ev = json.loads(line)
    except json.JSONDecodeError:
        continue
    if isinstance(ev, dict):
        ref = ev.get("sessionID") or ev.get("session_id") or ref
        part = ev.get("part") or ev
        if isinstance(part, dict) and part.get("type") == "text":
            text.append(part.get("text", ""))
if not text and raw.strip():
    text = [raw]
if rc == 124:  # coreutils timeout: shim-level call bound hit (AF_CALL_TIMEOUT_SECONDS)
    kind = "timeout"
elif rc != 0:
    kind = "crashed"
if not text and kind == "completed":
    kind = "crashed"
# cost_usd/tokens stay 0: OpenCode does not report cost to the shim. The supervisor
# therefore requires budget.max_provider_calls for OpenCode runs (enforceability gate).
print(json.dumps({"session_ref": ref, "text": "\n".join(text), "cost_usd": 0.0,
                  "tokens": 0, "exit_kind": kind}))
PY
